### ISSUE TITLE
Page right icon drops to the next line

### ISSUE THREAD

**Issue by sarxos** [tito433/Bootstrap-icon-picker#1]
Hi,

Thank you for this awesome icon picker for bootstrap. I noticed issue on the demo page. I'm using Firefox on Ubuntu 12.04.

![demo](https://f.cloud.github.com/assets/472658/2086654/264044a8-8e5c-11e3-96d4-2145dd242bf5.png)

This is most likely because of the `float: right` attribute not working in the rule:

``` css
.icon-popup .ip-control ul li:last-child {
    float: right;
    margin-right: 7px;
}
```

I suggest to change it to:

``` css
.icon-popup .ip-control ul li:last-child {
    position: absolute;
    right: 0;
    top: 14px;
    margin-right: 2px;
}
```
